import "./globals.css";

import type { Metadata } from "next";
import { Providers } from "./providers";
import { NavBar } from "@/features/shared/ui/NavBar";
import { Header } from "@/features/shared/ui/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="max-sm:mb-28 lg:w-9/12 mx-auto">
            <NavBar />
            <Header />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
