// import "./globals.css";
import { Providers } from "@/app/providers";
import { Header } from "@/features/shared/ui/Header";
import { NavBar } from "@/features/shared/ui/NavBar";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <NavBar />
      <Header />
      <div className="w-full h-auto flex justify-center items-center ">
        {children}
      </div>
    </Providers>
  );
}
