// import "./globals.css";
import { Providers } from "@/app/providers";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <div className="w-full h-auto flex justify-center items-center ">{children}</div>
    </Providers>
  );
}
